name: CI

on:
  push:
    branches:
      - main
      - "**"
  pull_request:
  workflow_dispatch:

env:
  dafny: "4.3.0"

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Install Dafny
        uses: dafny-lang/setup-dafny-action@v1
        with:
          dafny-version: ${{ env.dafny }}
      - uses: actions/checkout@v3
      - name: Verify
        run: dafny verify dafny/dfyconfig.toml
