name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Install Dafny
        uses: dafny-lang/setup-dafny-action@v1
      - uses: actions/checkout@v3
      - name: Verify
        run: dafny verify dafny/dfyconfig.yml
